require('dotenv').config(); // Load environment variables from .env file

const express = require('express');
const cors = require('cors');
const sgMail = require('@sendgrid/mail'); // Import SendGrid Mail
const app = express();
const port = 3001; // Choose a port different from the React app (default 5173)

// Set SendGrid API Key
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

app.use(cors()); // Enable CORS for all routes
app.use(express.json()); // Enable JSON body parsing


app.post('/api/identity-search', (req, res) => {
  const { name, keywords } = req.body;

  if (!name || !keywords) {
    return res.status(400).json({ error: 'Name and keywords are required.' });
  }

  const sanitizedName = name.toLowerCase().replace(/\s/g, '');
  const sanitizedKeywords = keywords.toLowerCase().replace(/\s/g, '-');
  const encodedName = encodeURIComponent(name);
  const encodedKeywords = encodeURIComponent(keywords);

  // Simulate searching the internet with enhanced social media presence
  const mockResults = [
    {
      title: `LinkedIn Profile: ${name}`,
      url: `https://www.linkedin.com/in/${sanitizedName}`,
      snippet: `Professional details for ${name} based on keywords like "${keywords}".`,
    },
    {
      title: `GitHub Profile: ${name.split(' ')[0]}`,
      url: `https://github.com/${sanitizedName}`,
      snippet: `Open-source projects and contributions from ${name} related to "${keywords}".`,
    },
    {
      title: `Academic Publication: "${keywords}" by ${name}`,
      url: `https://scholar.google.com/scholar?q=${encodedName}+${encodedKeywords}`,
      snippet: `A simulated academic paper or research mentioning ${name} and "${keywords}".`,
    },
    {
      title: `Blog Post: "Thoughts on ${keywords}" by ${name}`,
      url: `https://exampleblog.com/${sanitizedName}/thoughts-on-${sanitizedKeywords}`,
      snippet: `A personal blog entry by ${name} discussing aspects of "${keywords}".`,
    },
    {
      title: `Instagram Profile: @${sanitizedName}`,
      url: `https://www.instagram.com/${sanitizedName}`,
      snippet: `Visual content and public persona of ${name} related to "${keywords}".`,
    },
    {
      title: `Twitter (X) Feed: @${sanitizedName}`,
      url: `https://twitter.com/${sanitizedName}`,
      snippet: `Recent posts and public discussions by ${name} covering "${keywords}".`,
    },
    {
      title: `YouTube Channel: ${name}`,
      url: `https://www.youtube.com/@${sanitizedName}`,
      snippet: `Videos and media content from ${name}'s channel on topics like "${keywords}".`,
    },
    {
      title: `Facebook Profile: ${name}`,
      url: `https://www.facebook.com/public/${encodedName}`,
      snippet: `Public posts and community interactions of ${name} related to "${keywords}".`,
    },
  ];

  // Introduce a slight delay to simulate network latency
  setTimeout(() => {
    res.json({
      query: { name, keywords },
      results: mockResults,
      message: 'These results are simulated and generated by the local backend. No actual internet search was performed.',
    });
  }, 1000);
});

app.post('/api/artifact-scan', (req, res) => {
  const { hash } = req.body;

  if (!hash) {
    return res.status(400).json({ error: 'Hash value is required.' });
  }

  // Simulate scanning the artifact
  let status = 'Clean';
  let detectionRate = '0/70';
  let details = 'No threats detected by simulated engines.';

  // Example: some hashes could be "malicious" in this simulation
  if (hash.startsWith('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855')) { // SHA256 of empty string
    status = 'Clean';
    detectionRate = '0/70';
    details = 'Hash matches a known clean file.';
  } else if (hash.startsWith('d41d8cd98f00b204e9800998ecf8427e')) { // MD5 of empty string
    status = 'Clean';
    detectionRate = '0/70';
    details = 'Hash matches a known clean file.';
  } else if (hash.includes('malicious') || hash.includes('threat')) { // Simple check for demo
    status = 'Malicious';
    detectionRate = '65/70';
    details = 'Simulated detection of potential malware characteristics.';
  } else if (hash.length === 32 && (parseInt(hash.substring(0,2), 16) % 2) === 0) { // Simulate some random detections for MD5
    status = 'Unknown';
    detectionRate = '5/70';
    details = 'Simulated detection by a few engines. Further analysis recommended.';
  } else if (hash.length === 64 && (parseInt(hash.substring(0,2), 16) % 3) === 0) { // Simulate some random detections for SHA256
    status = 'Potentially Unwanted';
    detectionRate = '15/70';
    details = 'Simulated detection by multiple engines. Might be a PUP.';
  }

  setTimeout(() => {
    res.json({
      hash,
      status,
      detectionRate,
      details,
      message: 'This scan report is simulated and generated by the local backend. No actual virus scan was performed.',
    });
  }, 1500); // Longer delay to simulate scan time
});

// --- Contact Form Email Sending Endpoint ---
app.post('/api/contact', async (req, res) => {
  const { name, email, phoneNumber, message } = req.body;

  // Basic validation
  if (!name || !email || !message) {
    return res.status(400).json({ msg: 'Please enter all required fields: Name, Email, and Message.' });
  }

  // Define email content for SendGrid
  const msg = {
    to: process.env.EMAIL_TO, // Recipient email address from .env
    from: process.env.EMAIL_FROM, // Must be a verified sender in SendGrid
    subject: `New Contact Form Message from ${name}`,
    html: `
      <p>You have received a new message from your portfolio contact form.</p>
      <h3>Contact Details:</h3>
      <ul>
        <li>Name: ${name}</li>
        <li>Email: ${email}</li>
        <li>Phone Number: ${phoneNumber || 'N/A'}</li>
      </ul>
      <h3>Message:</h3>
      <p>${message}</p>
      <p>Sender's Email (Reply-To): ${email}</p>
    `,
    replyTo: email, // Set reply-to to sender's email
  };

  // Immediately acknowledge the request
  res.status(200).json({ msg: 'Your message has been received and is being processed. Thank you!' });

  // --- Send Email in the Background ---
  // Now, attempt to send the email without making the client wait.
  try {
    await sgMail.send(msg);
    console.log('Email sent successfully via SendGrid!');
  } catch (error) {
    console.error('Error sending email via SendGrid:', error);
    if (error.response && error.response.body) {
      console.error('SendGrid Error Response (Contact Form):', error.response.body);
    } else {
      console.error('SendGrid Error Message (Contact Form):', error.message);
    }
  }
});


// --- SendGrid Test Endpoint ---
app.post('/api/test-sendgrid', async (req, res) => {
  const msg = {
    to: process.env.EMAIL_TO,
    from: process.env.EMAIL_FROM, // IMPORTANT: This must be a verified sender in your SendGrid account.
    subject: 'SendGrid Test from Portfolio App',
    text: 'This is a test email from your portfolio application.',
    html: '<strong>This is a test email from your portfolio application.</strong>',
  };

  try {
    await sgMail.send(msg);
    console.log('Test email sent successfully via SendGrid!');
    res.status(200).json({ msg: `Test email sent successfully to ${process.env.EMAIL_TO}!` });
  } catch (error) {
    console.error('Error sending test email via SendGrid:', error);
    if (error.response && error.response.body) {
      console.error('SendGrid Error Response (Test Email):', error.response.body);
    } else {
      console.error('SendGrid Error Message (Test Email):', error.message);
    }
    res.status(500).json({ msg: 'Failed to send test email. Check server logs for details.' });
  }
});

app.listen(port, () => {
  console.log(`Backend server listening at http://localhost:${port}`);
  // Warn if environment variables are not set
  if (!process.env.SENDGRID_API_KEY) {
    console.warn('\nWARNING: SENDGRID_API_KEY environment variable is not set.');
    console.warn('Email sending functionality will not work until this is configured.');
    console.warn('Please obtain a SendGrid API Key and set it in your .env file.\n');
  }
});
process.on('uncaughtException', (err, origin) => {
  console.error('Caught exception:', err);
  console.error('Exception origin:', origin);
});
